apiVersion: v1
kind: Secret
metadata:
  name: cb-creds
  namespace: tap-install
stringData:
  cbc_api_id: CBC-API-ID
  cbc_api_key: CBC-API-KEY
  cbc_org_key: CBC-ORG-KEY
  cbc_saas_url: CBC-SAAS-URL
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: cb-creds
  namespace: tap-install
spec:
  toNamespace: '*'
