---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cosign-key-pair
  namespace: tap-install
data:
  cosign.key: PRIVATE-KEY-DATA
  cosign.password: COSIGN-PASSWORD
  cosign.pub: PUBLIC-KEY-DATA
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: cosign-key-pair
  namespace: tap-install
spec:
  toNamespace: '*'

